project:
  type: website
  output-dir: docs
  
  
website:
  title: "Rachel's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Resume.qmd
      - Projects.qmd

format:
  html:
    theme:
      - solana
    css: styles.css
    toc: true

editor: visual

